[2023-10-22T12:43:57.862+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL.Upload_Data manual__2023-10-22T12:43:56.379781+00:00 [queued]>
[2023-10-22T12:43:57.873+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL.Upload_Data manual__2023-10-22T12:43:56.379781+00:00 [queued]>
[2023-10-22T12:43:57.873+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-22T12:43:57.891+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): Upload_Data> on 2023-10-22 12:43:56.379781+00:00
[2023-10-22T12:43:57.898+0000] {standard_task_runner.py:57} INFO - Started process 516 to run task
[2023-10-22T12:43:57.901+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ETL', 'Upload_Data', 'manual__2023-10-22T12:43:56.379781+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/first_dags.py', '--cfg-path', '/tmp/tmp8wvoatgy']
[2023-10-22T12:43:57.903+0000] {standard_task_runner.py:85} INFO - Job 24: Subtask Upload_Data
[2023-10-22T12:43:57.940+0000] {task_command.py:416} INFO - Running <TaskInstance: ETL.Upload_Data manual__2023-10-22T12:43:56.379781+00:00 [running]> on host 460880db6b82
[2023-10-22T12:43:58.020+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='me' AIRFLOW_CTX_DAG_ID='ETL' AIRFLOW_CTX_TASK_ID='Upload_Data' AIRFLOW_CTX_EXECUTION_DATE='2023-10-22T12:43:56.379781+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-22T12:43:56.379781+00:00'
[2023-10-22T12:43:58.021+0000] {sql.py:274} INFO - Executing: 
        SELECT current_database();

        
[2023-10-22T12:43:58.028+0000] {base.py:73} INFO - Using connection ID 'postgres_docker' for task execution.
[2023-10-22T12:43:58.038+0000] {base.py:73} INFO - Using connection ID 'postgres_docker' for task execution.
[2023-10-22T12:43:58.046+0000] {sql.py:418} INFO - Running statement: 
        SELECT current_database();

        , parameters: None
[2023-10-22T12:43:58.048+0000] {sql.py:427} INFO - Rows affected: 1
[2023-10-22T12:43:58.067+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ETL, task_id=Upload_Data, execution_date=20231022T124356, start_date=20231022T124357, end_date=20231022T124358
[2023-10-22T12:43:58.114+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-22T12:43:58.129+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
