[2023-10-21T11:50:57.144+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dagg.scrape_data manual__2023-10-21T11:50:56.276978+00:00 [queued]>
[2023-10-21T11:50:57.153+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dagg.scrape_data manual__2023-10-21T11:50:56.276978+00:00 [queued]>
[2023-10-21T11:50:57.153+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-21T11:50:57.168+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): scrape_data> on 2023-10-21 11:50:56.276978+00:00
[2023-10-21T11:50:57.174+0000] {standard_task_runner.py:57} INFO - Started process 1936 to run task
[2023-10-21T11:50:57.176+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'first_dagg', 'scrape_data', 'manual__2023-10-21T11:50:56.276978+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/first_dags.py', '--cfg-path', '/tmp/tmpc7f1yr40']
[2023-10-21T11:50:57.179+0000] {standard_task_runner.py:85} INFO - Job 9: Subtask scrape_data
[2023-10-21T11:50:57.220+0000] {task_command.py:416} INFO - Running <TaskInstance: first_dagg.scrape_data manual__2023-10-21T11:50:56.276978+00:00 [running]> on host 694ad72b43d0
[2023-10-21T11:50:57.293+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='me' AIRFLOW_CTX_DAG_ID='first_dagg' AIRFLOW_CTX_TASK_ID='scrape_data' AIRFLOW_CTX_EXECUTION_DATE='2023-10-21T11:50:56.276978+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-21T11:50:56.276978+00:00'
[2023-10-21T11:50:57.294+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-10-21T11:50:57.294+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'bash /home/vertikal/data_science/web_scrap/rumah/rumah/script2.sh ']
[2023-10-21T11:50:57.303+0000] {subprocess.py:86} INFO - Output:
[2023-10-21T11:50:57.306+0000] {subprocess.py:93} INFO - bash: /home/vertikal/data_science/web_scrap/rumah/rumah/script2.sh: No such file or directory
[2023-10-21T11:50:57.307+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-10-21T11:50:57.316+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-10-21T11:50:57.321+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=first_dagg, task_id=scrape_data, execution_date=20231021T115056, start_date=20231021T115057, end_date=20231021T115057
[2023-10-21T11:50:57.334+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 9 for task scrape_data (Bash command failed. The command returned a non-zero exit code 127.; 1936)
[2023-10-21T11:50:57.348+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-21T11:50:57.363+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
