[2023-10-26T10:13:29.577+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL.upload_to_drive manual__2023-10-26T10:13:27.862442+00:00 [queued]>
[2023-10-26T10:13:29.585+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL.upload_to_drive manual__2023-10-26T10:13:27.862442+00:00 [queued]>
[2023-10-26T10:13:29.585+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-26T10:13:29.600+0000] {taskinstance.py:1382} INFO - Executing <Task(SSHOperator): upload_to_drive> on 2023-10-26 10:13:27.862442+00:00
[2023-10-26T10:13:29.609+0000] {standard_task_runner.py:57} INFO - Started process 386 to run task
[2023-10-26T10:13:29.613+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ETL', 'upload_to_drive', 'manual__2023-10-26T10:13:27.862442+00:00', '--job-id', '133', '--raw', '--subdir', 'DAGS_FOLDER/first_dags.py', '--cfg-path', '/tmp/tmpmy5tk7ss']
[2023-10-26T10:13:29.621+0000] {standard_task_runner.py:85} INFO - Job 133: Subtask upload_to_drive
[2023-10-26T10:13:29.690+0000] {task_command.py:416} INFO - Running <TaskInstance: ETL.upload_to_drive manual__2023-10-26T10:13:27.862442+00:00 [running]> on host 3d90f4ff5680
[2023-10-26T10:13:29.778+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='me' AIRFLOW_CTX_DAG_ID='ETL' AIRFLOW_CTX_TASK_ID='upload_to_drive' AIRFLOW_CTX_EXECUTION_DATE='2023-10-26T10:13:27.862442+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-26T10:13:27.862442+00:00'
[2023-10-26T10:13:29.779+0000] {ssh.py:135} INFO - Creating ssh_client
[2023-10-26T10:13:29.812+0000] {ssh.py:112} INFO - ssh_hook is not provided or invalid. Trying ssh_conn_id to create SSHHook.
[2023-10-26T10:13:29.819+0000] {base.py:73} INFO - Using connection ID 'host_machine' for task execution.
[2023-10-26T10:13:29.820+0000] {ssh.py:300} WARNING - No Host Key Verification. This won't protect against Man-In-The-Middle attacks
[2023-10-26T10:13:29.830+0000] {transport.py:1893} INFO - Connected (version 2.0, client OpenSSH_8.9p1)
[2023-10-26T10:13:29.987+0000] {transport.py:1893} INFO - Authentication (password) successful!
[2023-10-26T10:13:29.988+0000] {ssh.py:476} INFO - Running command: cd /home/***/data_science/power_bi && python3 drive_upload.py  
[2023-10-26T10:13:30.130+0000] {ssh.py:527} WARNING - Traceback (most recent call last):
[2023-10-26T10:13:30.131+0000] {ssh.py:527} WARNING -   File "/home/***/data_science/power_bi/drive_upload.py", line 1, in <module>
[2023-10-26T10:13:30.131+0000] {ssh.py:527} WARNING -     import gspread
[2023-10-26T10:13:30.131+0000] {ssh.py:527} WARNING - ModuleNotFoundError: No module named 'gspread'
[2023-10-26T10:13:30.162+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/ssh/operators/ssh.py", line 173, in execute
    result = self.run_ssh_client_command(ssh_client, self.command, context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/ssh/operators/ssh.py", line 161, in run_ssh_client_command
    self.raise_for_status(exit_status, agg_stderr, context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/ssh/operators/ssh.py", line 154, in raise_for_status
    raise AirflowException(f"SSH operator error: exit status = {exit_status}")
airflow.exceptions.AirflowException: SSH operator error: exit status = 1
[2023-10-26T10:13:30.165+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=ETL, task_id=upload_to_drive, execution_date=20231026T101327, start_date=20231026T101329, end_date=20231026T101330
[2023-10-26T10:13:30.175+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 133 for task upload_to_drive (SSH operator error: exit status = 1; 386)
[2023-10-26T10:13:30.197+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-26T10:13:30.212+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
