[2023-10-25T06:42:38.594+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL.get_csv manual__2023-10-25T06:42:37.454572+00:00 [queued]>
[2023-10-25T06:42:38.602+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL.get_csv manual__2023-10-25T06:42:37.454572+00:00 [queued]>
[2023-10-25T06:42:38.602+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-25T06:42:38.613+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): get_csv> on 2023-10-25 06:42:37.454572+00:00
[2023-10-25T06:42:38.623+0000] {standard_task_runner.py:57} INFO - Started process 370 to run task
[2023-10-25T06:42:38.625+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ETL', 'get_csv', 'manual__2023-10-25T06:42:37.454572+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/first_dags.py', '--cfg-path', '/tmp/tmp3v8ui34t']
[2023-10-25T06:42:38.628+0000] {standard_task_runner.py:85} INFO - Job 58: Subtask get_csv
[2023-10-25T06:42:38.667+0000] {task_command.py:416} INFO - Running <TaskInstance: ETL.get_csv manual__2023-10-25T06:42:37.454572+00:00 [running]> on host 82d3eba4e992
[2023-10-25T06:42:38.734+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='me' AIRFLOW_CTX_DAG_ID='ETL' AIRFLOW_CTX_TASK_ID='get_csv' AIRFLOW_CTX_EXECUTION_DATE='2023-10-25T06:42:37.454572+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-25T06:42:37.454572+00:00'
[2023-10-25T06:42:38.742+0000] {base.py:73} INFO - Using connection ID 'postgres_docker' for task execution.
[2023-10-25T06:42:38.757+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2023-10-25T06:42:38.777+0000] {logging_mixin.py:151} INFO - direcccccccccccccccccccccc /opt/***
[2023-10-25T06:42:38.778+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-10-25T06:42:38.786+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ETL, task_id=get_csv, execution_date=20231025T064237, start_date=20231025T064238, end_date=20231025T064238
[2023-10-25T06:42:38.801+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-25T06:42:38.814+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
