[2023-10-21T12:14:25.956+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dagg.scrape_data manual__2023-10-21T12:14:24.895635+00:00 [queued]>
[2023-10-21T12:14:25.964+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dagg.scrape_data manual__2023-10-21T12:14:24.895635+00:00 [queued]>
[2023-10-21T12:14:25.964+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-21T12:14:25.979+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): scrape_data> on 2023-10-21 12:14:24.895635+00:00
[2023-10-21T12:14:25.985+0000] {standard_task_runner.py:57} INFO - Started process 2541 to run task
[2023-10-21T12:14:25.987+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'first_dagg', 'scrape_data', 'manual__2023-10-21T12:14:24.895635+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/first_dags.py', '--cfg-path', '/tmp/tmpl1irfpyt']
[2023-10-21T12:14:25.989+0000] {standard_task_runner.py:85} INFO - Job 17: Subtask scrape_data
[2023-10-21T12:14:26.030+0000] {task_command.py:416} INFO - Running <TaskInstance: first_dagg.scrape_data manual__2023-10-21T12:14:24.895635+00:00 [running]> on host 694ad72b43d0
[2023-10-21T12:14:26.110+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='me' AIRFLOW_CTX_DAG_ID='first_dagg' AIRFLOW_CTX_TASK_ID='scrape_data' AIRFLOW_CTX_EXECUTION_DATE='2023-10-21T12:14:24.895635+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-21T12:14:24.895635+00:00'
[2023-10-21T12:14:26.119+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 197, in execute
    raise AirflowException(f"Can not find the cwd: {self.cwd}")
airflow.exceptions.AirflowException: Can not find the cwd: /home/vertikal/data_science/web_scrap/rumah/rumah/ 
[2023-10-21T12:14:26.124+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=first_dagg, task_id=scrape_data, execution_date=20231021T121424, start_date=20231021T121425, end_date=20231021T121426
[2023-10-21T12:14:26.135+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 17 for task scrape_data (Can not find the cwd: /home/vertikal/data_science/web_scrap/rumah/rumah/ ; 2541)
[2023-10-21T12:14:26.160+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-21T12:14:26.176+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
